apiVersion: apps/v1
kind: Deployment
metadata:
   name: mydeployments
spec:
   replicas: 2
   selector:
    matchLabels:
     name: deployment
   template:
     metadata:
       name: mypod
       labels:
         name: deployment
     spec:
      containers:
        - name: myc1
          image: jenkins/jenkins
          command: ["/bin/bash", "-c", "while true; do echo Technical-Guftgu; sleep 5; done"]

