apiVersion: apps/v1
kind: Deployment
metadata:
   name: mydeployments
   namespace: mystage
spec:
   replicas: 5
   selector:
    matchLabels:
     name: deployment
   template:
     metadata:
       name: mypod
       labels:
         name: deployment
     spec:
      containers:
        - name: myc1
          image: jenkins/jenkins
          command: ["/bin/bash", "-c", "while true; do echo wellcome bengaluru; sleep 10; done"]

